version: "3.1"
services:

  mysql5.7:
    image: mysql:5.7
    container_name: mysql5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/db:/var/lib/mysql
    ports:
      - "3306:3306"

  mysql8.3:
    image: mysql:8.3
    container_name: mysql8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/db2:/var/lib/mysql
    ports:
      - "3307:3306"

  redis6.0:
    image: redis:6.0.16
    container_name: redis6.0
    volumes:
      - ./app/redis/data:/data
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php7.3
      - php7.4
      - php8.0
      - php8.1
      - php8.2

  php7.3:
    build:
      context: ./config/php7.3
      dockerfile: Dockerfile
    container_name: php7.3
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php7.3/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost

  php7.4:
    build:
      context: ./config/php7.4
      dockerfile: Dockerfile
    container_name: php7.4
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php7.4/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
        PHP_IDE_CONFIG: serverName=localhost

  php8.0:
    build:
      context: ./config/php8.0
      dockerfile: Dockerfile
    container_name: php8.0
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php8.0/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
      PHP_IDE_CONFIG: serverName=localhost

  php8.1:
    build:
      context: config/php8.1
      dockerfile: Dockerfile
    container_name: php8.1
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php8.1/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
      PHP_IDE_CONFIG: serverName=localhost

  php8.2:
    build:
      context: config/php8.2
      dockerfile: Dockerfile
    container_name: php8.2
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php8.2/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    environment:
      PHP_IDE_CONFIG: serverName=localhost

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    volumes:
      - ./app/log/maildev:/var/maildev
    environment:
      MAILDEV_MAIL_DIRECTORY: /var/maildev

# Change default subnet addresses (for uncomment - delete only '#'):
#networks:
#  default:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 10.10.0.1/16
